### ISSUE TITLE
logistic model with NaNs for standard errors

### ISSUE THREAD

**Issue by craigenders** [alexanderrobitzsch/mdmb#1]
Hi Alexander,
I wanted to share with you an example where mdmb fails to print SEs for a logistic regression.
Best,
Craig Enders
<img width="816" alt="Screenshot 2022-11-20 at 1 52 42 PM" src="https://user-images.githubusercontent.com/16941177/202928210-1b909ae0-39b4-4186-9827-2fd1cb71825f.png">
[behaviorachievement.dat.txt](https://github.com/alexanderrobitzsch/mdmb/files/10050776/behaviorachievement.dat.txt)
[Ex2.1.R.txt](https://github.com/alexanderrobitzsch/mdmb/files/10050777/Ex2.1.R.txt)

**Comment by alexanderrobitzsch** [comment]
I had a recent release that likely solved this issue.
